# MCAN configuration
model:
  name: "mcan"
  vocab_size: 10000
  embed_dim: 512
  hidden_dim: 1024
  num_answers: 3129
  learning_rate: 1e-3
  weight_decay: 1e-4
  num_layers: 6
  num_heads: 8
  pretrained: true

data:
  data_dir: "data/vqa_v2"
  max_question_length: 20
  image_size: 224
  batch_size: 32
  num_workers: 4

training:
  max_epochs: 50
  val_check_interval: 0.25
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  early_stopping_patience: 5

logging:
  log_every_n_steps: 100
  save_top_k: 3
  monitor: "val_loss"
  mode: "min" 